### ISSUE TITLE
大神，这个grafana百度地图的插件什么时候开发好呢

### ISSUE THREAD

**Issue by liuhaibo0303** [shcolo/grafana-baidumap-panel#1]
大神，这个grafana百度地图的插件什么时候开发好呢

**Comment by ofDamon** [comment]
@liuhaibo0303 目前已经是一个可用的版本，暂时不会继续开发

**Comment by liuhaibo0303** [comment]
这个百度地图的插件，我对接的是ES的数据源，想展示城市热点图，但是配置了，感觉好像没什么变化，求指导
![image](https://user-images.githubusercontent.com/32126569/62097847-df358a80-b2ba-11e9-83e9-435bb836a1b2.png)
![image](https://user-images.githubusercontent.com/32126569/62097881-fe341c80-b2ba-11e9-880b-257c8461e4ba.png)

**Comment by ofDamon** [comment]
> 这个百度地图的插件，我对接的是ES的数据源，想展示城市热点图，但是配置了，感觉好像没什么变化，求指导
> ![图片](https://user-images.githubusercontent.com/32126569/62097847-df358a80-b2ba-11e9-83e9-435bb836a1b2.png)
> ![图片](https://user-images.githubusercontent.com/32126569/62097881-fe341c80-b2ba-11e9-880b-257c8461e4ba.png)

Location Data选json result或table

**Comment by liuhaibo0303** [comment]
![image](https://user-images.githubusercontent.com/32126569/62435892-58782600-b770-11e9-81fb-cd19d3d5ee06.png)
![image](https://user-images.githubusercontent.com/32126569/62435922-780f4e80-b770-11e9-85f3-94ef0bfb9418.png)

好像还是没有变化

**Comment by huizhong** [comment]
有成功的使用示例么？我这用worldmap能成功展示，但百度地图这显示不出来。
<img width="1111" alt="Screen Shot 2019-09-09 at 9 32 22 PM" src="https://user-images.githubusercontent.com/4644560/64535171-61e54700-d349-11e9-967a-16c70bc84556.png">

**Comment by huizhong** [comment]
> ![image](https://user-images.githubusercontent.com/32126569/62435892-58782600-b770-11e9-81fb-cd19d3d5ee06.png)
> ![image](https://user-images.githubusercontent.com/32126569/62435922-780f4e80-b770-11e9-85f3-94ef0bfb9418.png)
> 
> 好像还是没有变化

追了下源码，终于搞定了。。。 这个魔改是直接把原来一套跳过了，指定两种类型，写了三个硬名称。
我这边是直接查mysql。所以选json result。
然后在查询结果按 lat,lng,rssi 命名，就能得到结果

<img width="953" alt="Screen Shot 2019-09-10 at 11 25 52 AM" src="https://user-images.githubusercontent.com/4644560/64581734-dc4fae80-d3bd-11e9-987b-261733f8ed16.png">

**Comment by ofDamon** [comment]
> > ![image](https://user-images.githubusercontent.com/32126569/62435892-58782600-b770-11e9-81fb-cd19d3d5ee06.png)
> > ![image](https://user-images.githubusercontent.com/32126569/62435922-780f4e80-b770-11e9-85f3-94ef0bfb9418.png)
> > 好像还是没有变化
> 
> 追了下源码，终于搞定了。。。 这个魔改是直接把原来一套跳过了，指定两种类型，写了三个硬名称。
> 我这边是直接查mysql。所以选json result。
> 然后在查询结果按 lat,lng,rssi 命名，就能得到结果
> 
> <img alt="Screen Shot 2019-09-10 at 11 25 52 AM" width="953" src="https://user-images.githubusercontent.com/4644560/64581734-dc4fae80-d3bd-11e9-987b-261733f8ed16.png">

是的，当初修改的时候，只是针对我当时需要用的数据格式来做了，可按需修改
