### ISSUE TITLE
Elasticsearch数据源地图展示不出来

### ISSUE THREAD

**Issue by xiaoxuan220** [shcolo/grafana-baidumap-panel#2]
前辈你好，请教一下关于数据源为ES，地图展示不出来的问题
ES Vsersion：5.6.4
Grafana Version：6.3
![2](https://user-images.githubusercontent.com/22339743/65005116-61444600-d931-11e9-8abb-0b773922169d.png)
![1](https://user-images.githubusercontent.com/22339743/65005127-6903ea80-d931-11e9-8ebf-5c0d542ec872.png)
具体配置如上图，地图还是不出来，麻烦问下应该如何配置，多谢！

**Comment by ofDamon** [comment]
> 前辈你好，请教一下关于数据源为ES，地图展示不出来的问题
> ES Vsersion：5.6.4
> Grafana Version：6.3
> ![2](https://user-images.githubusercontent.com/22339743/65005116-61444600-d931-11e9-8abb-0b773922169d.png)
> ![1](https://user-images.githubusercontent.com/22339743/65005127-6903ea80-d931-11e9-8ebf-5c0d542ec872.png)
> 具体配置如上图，地图还是不出来，麻烦问下应该如何配置，多谢！
Location Data选json result，查询结果按 lat lng rssi 命名

**Comment by xiaoxuan220** [comment]
> > 前辈你好，请教一下关于数据源为ES，地图展示不出来的问题
> > ES Vsersion：5.6.4
> > Grafana Version：6.3
> > ![2](https://user-images.githubusercontent.com/22339743/65005116-61444600-d931-11e9-8abb-0b773922169d.png)
> > ![1](https://user-images.githubusercontent.com/22339743/65005127-6903ea80-d931-11e9-8ebf-5c0d542ec872.png)
> > 具体配置如上图，地图还是不出来，麻烦问下应该如何配置，多谢！
> > Location Data选json result，查询结果按 lat lng rssi 命名
===================================================
多谢您的回复，我用的是ES接收的nginx日志，具体ES里面的记录如下：
{
"_index": "logstash-2019.09.03",
"_type": "log",
"_id": "AWz10xrstr1lQHWyuqzI",
"_version": 1,
"_score": 1,
"_source": {
"request": "/wx/user/ab/qwezxdfrl8",
"agent": ""Mozilla/5.0 (iPhone; CPU iPhone OS 12_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/7.0.4(0x17000428) NetType/WIFI Language/zh_CN"",
"minor": "4",
"auth": "-",
"ident": "-",
"upstream_addr": "10.10.10.10:880",
"wxversion": "7.0.4",
"os_minor": "4",
"os_major": "12",
"source": "/nginx/logs/access.log",
"type": "log",
"request_time": 0.006,
"major": "12",
"clientip": "30.30.30.30",
"@version": "1",
"beat": { "hostname": "ng2","name": "filebeat_ng2","version": "5.0.0"},
"host": "ng2",
"geoip": {
"timezone": null,
"ip": "30.30.30.30",
"latitude": 34.7725,
"continent_code": "AS",
"city_name": Shanghai,
"country_code2": "CN",
"country_name": "China",
"dma_code": null,
"country_code3": "CN",
"region_name": null,
"location": [
113.7266
,
34.7725
],
"postal_code": null,
"longitude": 113.7266,
"region_code": null
},
"offset": 691339912,
"os": "iOS 12.4",
"input_type": "log",
"verb": "GET",
"message": "message......",
"tags": [
"ng2"
,
"beats_input_codec_plain_applied"
],
"referrer": ""https://www.xxx.com/views/index.html"",
"@timestamp": "2019-09-03T06:31:27.000Z",
"response": 200,
"bytes": 33,
"http_x_forwarded_for": "-",
"name": "Mobile Safari",
"os_name": "iOS",
"httpversion": "1.1",
"upstream_response_time": 0.006,
"fields": {
"env": "ab"
},
"device": "iPhone"
}
}
因为ES里面已有数据，改字段名称比较难，劳烦再指教一下怎么改源码吧，谢谢！

**Comment by ofDamon** [comment]
@xiaoxuan220 在/src/baidumap_ctrl.js里面，translateOne方法里面对translatedElements的循环那里可以修改下
