### ISSUE TITLE
在Grafana 6.x上无法工作

### ISSUE THREAD

**Issue by forever765** [shcolo/grafana-baidumap-panel#4]
感谢您的付出，但该插件在Grafana 6.x上已经无法工作，我的Grafana版本：v6.6.1
加载插件时没有地图显示，在v5.4.3上则可以正常工作，请问是否有计划支持Grafana 6.x？

**Comment by ofDamon** [comment]
@forever765 不好意思，暂时没有支持Grafana 6.x的计划
