### ISSUE TITLE
这个百度地图可以对接es数据源吗？

### ISSUE THREAD

**Issue by leeredstar** [shcolo/grafana-baidumap-panel#5]
这个百度地图可以对接es数据源吗？
我设置了一下，不好使

**Comment by shcolo** [comment]
选json result，然后在查询结果按 lat,lng,rssi 命名

**Comment by ofDamon** [comment]
> 这个百度地图可以对接es数据源吗？
> 我设置了一下，不好使

选json result，然后在查询结果按 lat,lng,rssi 命名
